-- CREATE TABLE users (
-- 	id SERIAL PRIMARY KEY,
-- 	name VARCHAR(100) NOT NULL,
-- 	email VARCHAR(120) NOT NULL UNIQUE
-- );

-- INSERT INTO users (name, email) 
-- VALUES 
-- 	('Ayan', 'ayan@mail.com'),
-- 	('Madiyar', 'madiyar@mail.com'),
-- 	('Dana', 'dana@mail.com');